### ISSUE TITLE
error at 'CnR_S2_A_Aln_Ref (treat_1)'

### ISSUE THREAD

**Issue by mhriris** [RenneLab/CnR-flow#6] opened 2022-10-28 16:07 UTC
Hello again, when I run for one sample as test with treat file I get this error when the pipeline arrive to the alignment step :
![Image11](https://user-images.githubusercontent.com/57253567/198682214-5e04acda-4a76-4061-84a6-31e8043ca61d.png)

running same command in a local environnement (with Bowtie2/2.4.2) works perfectly. I tryied with several docker images of Bowtie2 and always got same error.
Thanks in advance!

**Comment by dstrib** [comment] 2022-10-28 16:13
Hi! Would you mind copying the error text or output text so I can see where the problem is?
Thanks!

**Comment by mhriris** [comment] 2022-10-28 16:16
Command error:
  bowtie2 -p 24 \
                         --phred33 -I 10 -X 700 --dovetail --no-unal --no-mixed --no-discordant \
                         -x [path]/mm10_bt2_db/mm10 \
                         -1 [sample_1].fastq.gz \
                         -2 [sample_2].fastq.gz \
                           | samtools view -bS - \
                             > S2_A_aln_ref/sample.bam
  (ERR): "[path]/mm10_bt2_db/mm10" does not exist or is not a Bowtie 2 index
  Exiting now ...
  [main_samview] fail to read the header from "-".

Work dir:
  [work_path]/f5/77fa1f02a7ef589672e34c99b01482

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

**Comment by dstrib** [comment] 2022-10-28 16:34
Ahh here is where the problem is: 
(ERR): "[reference_path]/./mm10_bt2_db/mm10" does not exist or is not a Bowtie 2 index
Exiting now ...
Can you confirm that this directory exists and has a bowtie2 index with prefix "mm10" in it?

If it does, this is then likely another Singularity path-mounting issue.

**Comment by mhriris** [comment] 2022-10-28 16:38
yep, Here is the folder 
[xxx@login005 mm10_bt2_db]$ cd [reference_path]/./mm10_bt2_db/
[xxx@login005 mm10_bt2_db]$ ls -lrh
total 3.6G
[files]

**Comment by dstrib** [comment] 2022-10-28 16:38
Are there any symlinks in that path?

**Comment by mhriris** [comment] 2022-10-28 16:42
if you mean in [reference_path]/mm10_bt2_db/, no there is no symlinks there.

but in WORK directory, this one $HOME was created automatically when I run the pipeline in "initiate" mode

**Comment by dstrib** [comment] 2022-10-28 17:01
Ok, this might be something I need to correct in that step then to enable working with singularity.
Navigate to the directory with the bowtie2 directory and find the "physical" path with "pwd -p"
If your nextflow.config file has the parameter:
refs_dir     = "${launchDir}/cnr_references"
replace it with 
refs_dir    = "/abs/path/to/cnr_references"
if not, then just add the above line.
This should change where the pipe looks for the references dir for relative pathing to make the prefix absolute.
If that doesn't work, can you re-paste the new error output?
Thanks for your assistance in troubleshooting this! I apologize as I don't have this issue with the Singularity configuration at my institution.

**Comment by mhriris** [comment] 2022-10-28 17:16
Thank you so much! 

"Navigate to the directory with the bowtie2 directory"
Do you mean run **Bowtie2 docker** image then navigate to cnr_ref and run "pwd -p"?

**Comment by dstrib** [comment] 2022-10-28 17:28
Apologies, I meant navigate to the directory with the bowtie2 reference index! However, I think I misunderstood your previous message, and I don't think my last suggestion will help if the path to the reference does not contain any symlinks. Can you try running the pipeline again using the --verbose flag, and copying the part where it specifies the reference information that is detected? Also, would you like to reach out to me directly at [myemail] to avoid posting private details?

**Comment by dstrib** [comment] 2022-10-29 11:46
Issue fixed by adding the following to nextflow.config : 

`singularity.runOptions = "-B ${launchDir}:${launchDir}"`

**Closed as completed by dstrib** 2022-10-29 11:46 UTC
